import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { AuthenticatedTemplate, UnauthenticatedTemplate } from "@azure/msal-react"
import Login from '@/components/login'
import Dashboard from '@/components/dashboard'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <UnauthenticatedTemplate>
        <Head>
            <title>rint.si - Sign-In</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <Login />
        </main>
      </UnauthenticatedTemplate>

      <AuthenticatedTemplate>
        <Head>
          <title>rint.si - Dashboard</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <Dashboard />
        </main>
      </AuthenticatedTemplate>
    </>
  )
}
