import Head from 'next/head'
import { useMsal } from "@azure/msal-react"
import React, { useEffect } from 'react'
import { loginRequest } from '../auth/authConfig'
import { IPublicClientApplication, InteractionStatus } from '@azure/msal-browser'

type SignInButtonProps = {
    msalInstance: IPublicClientApplication
}

const SignInButton: React.FC<SignInButtonProps> = ({ msalInstance }) => {
    const handleButtonPress = () => {
        msalInstance.loginRedirect(loginRequest).catch(e => console.log(e))
    }
    return <button onClick={() => handleButtonPress()}>Sign-in</button>
}

export default function Login() {
    const { instance, inProgress } = useMsal();

    useEffect(() => {
        instance.loginPopup(loginRequest).catch(e => console.log(e))
    }, [instance])

    if (inProgress === InteractionStatus.None) {
        return (
            <>
                <Head>
                    <title>rint.si - Sign-In</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <SignInButton msalInstance={instance} />
            </>
        )
    }

    if (inProgress === InteractionStatus.Login) {
        return (
            <>
                <Head>
                    <title>rint.si - Sign-In</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <h1>Signing-in...</h1>
            </>
        )
    }

    return <h1>Wait..</h1>
}